---

- name: Production | Create projects directory global server
  file:
    path: '/home/{{ ansible_user }}/{{ item }}'
    state: directory
    mode: 0755
  loop:
    - projects/{{ org_name }}/config
    - projects/{{ org_name }}/config/admin-webapp
    - projects/{{ org_name }}/config/adminservice/storage
    - projects/{{ org_name }}/config/patientservice/storage
    - projects/{{ org_name }}/config/rocketchat
    - projects/{{ org_name }}/config/therapist-webapp
    - projects/{{ org_name }}/config/therapistservice/storage
    - projects/{{ org_name }}/config/libraryservice/storage

- name: Create organization network
  docker_network:
    name: '{{ org_name }}-network'

- name: Create docker compose file
  template:
    src: 'compose.yaml.j2'
    dest: '/home/{{ ansible_user }}/projects/{{ org_name }}/compose.yaml'
    mode: 0755

- name: Docker compose start all container
  docker_compose:
    project_src: '/home/{{ ansible_user }}/projects/{{ org_name }}'

- name: Wait for containers ready
  pause:
    seconds: 30
