---

# Run artisan admin service
- name: Run artisan migration
  shell: 'docker-compose exec admin-{{ org_name }}-service /usr/bin/php artisan migrate --force'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'

- name: Run artisan storage link
  shell: 'docker-compose exec admin-{{ org_name }}-service /usr/bin/php artisan storage:link'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'

- name: Run artisan clear cache
  shell: 'docker-compose exec admin-{{ org_name }}-service /usr/bin/php artisan {{ item }}'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear

- name: Run artisan import
  shell: 'docker-compose exec admin-{{ org_name }}-service /usr/bin/php artisan hi:import-default-translation'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'

# Run artisan therapist service
- name: Run artisan migration
  shell: 'docker-compose exec therapist-{{ org_name }}-service /usr/bin/php artisan migrate --force'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'

- name: Run artisan storage link
  shell: 'docker-compose exec therapist-{{ org_name }}-service /usr/bin/php artisan storage:link'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'

- name: Run artisan clear cache
  shell: 'docker-compose exec therapist-{{ org_name }}-service /usr/bin/php artisan {{ item }}'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear

# Run artisan patient service
- name: Run artisan migration
  shell: 'docker-compose exec patient-{{ org_name }}-service /usr/bin/php artisan migrate --force'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'

- name: Run artisan storage link
  shell: 'docker-compose exec patient-{{ org_name }}-service /usr/bin/php artisan storage:link'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'

- name: Run artisan clear cache
  shell: 'docker-compose exec patient-{{ org_name }}-service /usr/bin/php artisan {{ item }}'
  args:
    chdir: '/home/{{ ansible_user }}/projects/{{ org_name }}'
  loop:
    - cache:clear
    - config:clear
    - view:clear
    - route:clear
