---

# Traefik - Proxy
#- name: Deploy traefik service
#  import_tasks: 0-traefik.yaml

# Organization Service
- name: Create organization service
  import_tasks: 1-create-organization.yaml

# Create database
- name: Create database
  import_tasks: 2-create-database.yaml

# Laravel Migration
- name: Run migration
  import_tasks: 3-migrations.yaml
