# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
tz_path: "/usr/share/zoneinfo/Asia/Phnom_Penh"

image:
  repository: "hub.web-essentials.co/we/hiv-tra-20"
  stage: "latest"
  service: "admin"
  org_name: "webessentials"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: latest-admin.hi.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

