---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ include "meet.fullname" . }}
  labels:
    app: pv-{{ include "meet.fullname" . }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs_server.host }}
    path: {{ .Values.nfs_server.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "meet.fullname" . }}
spec:
  selector:
    matchLabels:
      app: pv-{{ include "meet.fullname" . }}
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
      storage: 2Gi
