apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meet.fullname" . }}-web
  labels:
    app: {{ include "meet.fullname" . }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "meet.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "meet.fullname" . }}-web
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          envFrom:
            - configMapRef:
                name: configmap-{{ include "meet.fullname" . }}
          volumeMounts:
            - name: 'vol-{{ include "meet.fullname" . }}'
              subPath: web
              mountPath: /config
            - name: 'vol-{{ include "meet.fullname" . }}'
              subPath: transcripts
              mountPath: /usr/share/jitsi-meet/transcripts

      volumes:
        - name: 'vol-{{ include "meet.fullname" . }}'
          persistentVolumeClaim:
            claimName: 'pvc-{{ include "meet.fullname" . }}'
