# Default values for krakend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
tz_path: "/usr/share/zoneinfo/Asia/Phnom_Penh"

image:
  repository: devopsfaith/krakend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.4.1"
image:
  repository: "hub.web-essentials.co/we/hiv-tra-20"
  org_name: "webessentials"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000
